version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
configuration: Release
test: off
environment:
  MY_VARIABLE: value
build_script:
  - ps: ./Build.ps1

artifacts:
- path: artifacts/AspNetCoreIdentityLocalizationTemplate.*.nupkg
- path: artifacts/AspNetCoreIdentityLocalizationTemplate.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: j45j302qWyN118IC53/Td8YjEkpmxcb3iSpZT67tlyT/SSb4GIVDRZ1Wak6Qiddy
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: SJhGDlty7WNVlwbZUrcn7YGjQdvkcEDqbXcqpBYPLb1iS1gaOhQSHhzeUZKJ/wJz
  artifacts:
    /AspNetCoreIdentityLocalizationTemplate.*\.nupkg/
    /AspNetCoreIdentityLocalizationTemplate.*\.snupkg/
  tag: $env:MY_VARIABLE
  on:
    branch: master
