version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
init:
  - git config --global core.autocrlf true
configuration: Release
test: off
build_script:
  - ps: ./Build.ps1

artifacts:
- path: artifacts/AspNetCoreIdentityLocalizationTemplate.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: uL49W96z8Cn7fBbogOcrV6IXiioG72jPhPfVnEXOM0mErBqA45HUE75NgqPPKPkL
  on:
    branch: /^(master|dev)$/
